# Generated by Django 4.2.3 on 2023-07-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_alunos_alter_turma_instrutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='qtd_minima_alunos',
            new_name='qtd_minimo_alunos',
        ),
    ]
