# Generated by Django 4.2.3 on 2023-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_rename_qtd_minimo_alunos_turma_qtd_minima_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='aceitando_matriculas',
            field=models.BooleanField(default=True),
        ),
    ]
