# Generated by Django 4.2.1 on 2023-05-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensagens',
            table='tb_mensagem',
        ),
    ]
