# Generated by Django 4.2.1 on 2023-05-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_alter_mensagens_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mensagens',
            table='tb_mensagens',
        ),
    ]
